#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Key {
    // Letters
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    // Numbers
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,

    // Special keys
    Escape,
    Tab,
    CapsLock,
    Shift,
    Control,
    Alt,
    Super,
    Space,
    Enter,
    Backspace,
    Delete,
    Insert,
    Home,
    End,
    PageUp,
    PageDown,

    // Arrow keys
    Up,
    Down,
    Left,
    Right,

    // Numpad
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadSubtract,
    NumpadMultiply,
    NumpadDivide,
    NumpadDecimal,
    NumpadEnter,

    // Symbols
    Apostrophe,
    Comma,
    Period,
    Slash,
    Semicolon,
    Equal,
    Minus,
    Backslash,
    Grave,
    BracketLeft,
    BracketRight,
}

impl From<glutin::event::VirtualKeyCode> for Key {
    fn from(key: glutin::event::VirtualKeyCode) -> Self {
        use glutin::event::VirtualKeyCode as VK;
        match key {
            VK::A => Key::A,
            VK::B => Key::B,
            VK::C => Key::C,
            VK::D => Key::D,
            VK::E => Key::E,
            VK::F => Key::F,
            VK::G => Key::G,
            VK::H => Key::H,
            VK::I => Key::I,
            VK::J => Key::J,
            VK::K => Key::K,
            VK::L => Key::L,
            VK::M => Key::M,
            VK::N => Key::N,
            VK::O => Key::O,
            VK::P => Key::P,
            VK::Q => Key::Q,
            VK::R => Key::R,
            VK::S => Key::S,
            VK::T => Key::T,
            VK::U => Key::U,
            VK::V => Key::V,
            VK::W => Key::W,
            VK::X => Key::X,
            VK::Y => Key::Y,
            VK::Z => Key::Z,
            VK::Key0 => Key::Key0,
            VK::Key1 => Key::Key1,
            VK::Key2 => Key::Key2,
            VK::Key3 => Key::Key3,
            VK::Key4 => Key::Key4,
            VK::Key5 => Key::Key5,
            VK::Key6 => Key::Key6,
            VK::Key7 => Key::Key7,
            VK::Key8 => Key::Key8,
            VK::Key9 => Key::Key9,
            VK::F1 => Key::F1,
            VK::F2 => Key::F2,
            VK::F3 => Key::F3,
            VK::F4 => Key::F4,
            VK::F5 => Key::F5,
            VK::F6 => Key::F6,
            VK::F7 => Key::F7,
            VK::F8 => Key::F8,
            VK::F9 => Key::F9,
            VK::F10 => Key::F10,
            VK::F11 => Key::F11,
            VK::F12 => Key::F12,
            VK::Escape => Key::Escape,
            VK::Tab => Key::Tab,
            //VK::CapsLock => Key::CapsLock,
            VK::LShift | VK::RShift => Key::Shift,
            VK::LControl | VK::RControl => Key::Control,
            VK::LAlt | VK::RAlt => Key::Alt,
            VK::LWin | VK::RWin => Key::Super,
            VK::Space => Key::Space,
            VK::Return => Key::Enter,
            VK::Back => Key::Backspace,
            VK::Delete => Key::Delete,
            VK::Insert => Key::Insert,
            VK::Home => Key::Home,
            VK::End => Key::End,
            VK::PageUp => Key::PageUp,
            VK::PageDown => Key::PageDown,
            VK::Up => Key::Up,
            VK::Down => Key::Down,
            VK::Left => Key::Left,
            VK::Right => Key::Right,
            VK::Numpad0 => Key::Numpad0,
            VK::Numpad1 => Key::Numpad1,
            VK::Numpad2 => Key::Numpad2,
            VK::Numpad3 => Key::Numpad3,
            VK::Numpad4 => Key::Numpad4,
            VK::Numpad5 => Key::Numpad5,
            VK::Numpad6 => Key::Numpad6,
            VK::Numpad7 => Key::Numpad7,
            VK::Numpad8 => Key::Numpad8,
            VK::Numpad9 => Key::Numpad9,
            VK::NumpadAdd => Key::NumpadAdd,
            VK::NumpadSubtract => Key::NumpadSubtract,
            VK::NumpadMultiply => Key::NumpadMultiply,
            VK::NumpadDivide => Key::NumpadDivide,
            VK::NumpadDecimal => Key::NumpadDecimal,
            VK::NumpadEnter => Key::NumpadEnter,
            VK::Apostrophe => Key::Apostrophe,
            VK::Comma => Key::Comma,
            VK::Period => Key::Period,
            VK::Slash => Key::Slash,
            VK::Semicolon => Key::Semicolon,
            VK::Equals => Key::Equal,
            VK::Minus => Key::Minus,
            VK::Backslash => Key::Backslash,
            VK::Grave => Key::Grave,
            VK::LBracket => Key::BracketLeft,
            VK::RBracket => Key::BracketRight,
            _ => Key::Space, // Fallback
        }
    }
}
